### ISSUE TITLE
Add support to release Linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [scoder/fastrlock#12]
Problem
---------
On aarch64, ‘pip install fastrlock’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi. 

Resolution
-----------
On aarch64, ‘pip install fastrlock’ should download the wheels from pypi 

@scoder Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by scoder** [comment]
I released fastrlock 0.8.3 with wheels up to Py3.13.
