### ISSUE TITLE
Not fast?

### ISSUE THREAD

**Issue by sonots** [scoder/fastrlock#2]
I wrote benchmark scripts as follows to compare:

lock_bench.py

```python
import time
import threading

lock = threading.RLock()

start_time = time.time()
for i in range(100000):
    lock.acquire()
    lock.release()
    # with lock:
    #     pass
elapsed_time = time.time() - start_time
print(elapsed_time)
```

fastrlock_bench.py

```python
import time
from fastrlock import rlock

lock = rlock.FastRLock()

start_time = time.time()
for i in range(100000):
    lock.acquire()
    lock.release()
    # with lock:
    #     pass
elapsed_time = time.time() - start_time
print(elapsed_time)
```

I obtained following results which show fastrlock is not fast.

```
$ python ~/lock_bench.py
0.03992772102355957
$ python ~/fastrlock_bench.py
0.04404258728027344
```

My python and cython version is as follows:

```
$ python --version
Python 3.6.1
$ cython --version
Cython version 0.25.2
```

Could you tell me if I am doing something wrong?

**Comment by scoder** [comment]
Interesting. I hadn't run benchmarks in a while. Looks like `threading.RLock` is faster starting with Py3.4. `FastRLock` is essentially unchanged since 2010. Probably no longer worth using these days then (well, except in Python 2 where the advantage is huge, or maybe also when called directly from Cython code).

**Comment by sonots** [comment]
Thank you!

**Comment by sonots** [comment]
Additional comments:

In the case of cython with FastRLock C API, fastrlock was pretty faster than `threading.RLock` even in Py3.6. Thanks!

**Comment by scoder** [comment]
Thanks for reporting back!
