### ISSUE TITLE
Wheels for Python 3.8

### ISSUE THREAD

**Issue by kmaehashi** [scoder/fastrlock#9]
It would be great if you provide wheels for Python 3.8.
Thanks!

**Comment by kmaehashi** [comment]
Hello @scoder, do you have any plans to work on this?
I'm maintaining [CuPy](https://github.com/cupy/cupy) which depends on this great package, and would like to allow users to install fastrlock without build process.
If you don't have time to work on, I can also contribute the wheel release if you give me permission to upload on PyPI.
Thank you in advance!

**Comment by scoder** [comment]
I uploaded a 0.5 that includes wheels for Py3.8.

**Comment by kmaehashi** [comment]
Thank you very much!
